# Gradle JVM 内存
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# AndroidX（minSdk 26 已全量 AndroidX，无需 Jetifier）
android.useAndroidX=true
android.enableJetifier=false

# Kotlin 代码风格
kotlin.code.style=official

# 并行构建（多模块项目有效）
org.gradle.parallel=true

# 构建缓存
org.gradle.caching=true

# 解决在 nspawn 沙箱中 libnative-platform.so 加载失败的问题
org.gradle.native=false
